services:
    PhpCsFixer\Fixer\Comment\HeaderCommentFixer:
        header: "This file is part of Contao Hello World Bundle.\n\n(c) Marko Cupic 2020 <m.cupic@gmx.ch>\n@license MIT\n@link https://github.com/markocupic/contao-hello-world-bundle\n"
